// Single source of truth for the Help Centre — used by /help and /help/[category].
// Answers are short, plain-English, and reference volpair's own vocabulary:
// Volley (romantic interest), Connect (play/partner), Play again (rematch),
// Serve (message), Match (mutual Volley), volpair Score (compatibility).

export const HELP_CATEGORIES = [
  {
    slug: 'getting-started',
    emoji: '🚀',
    title: 'Getting started',
    desc: 'Create your account and set up your profile.',
    articles: [
      { q: 'How do I create an account?',
        a: 'Download volpair from the App Store or Google Play, then sign up with your email. You must be 18 or over to use volpair.' },
      { q: 'How do I build a good profile?',
        a: 'Add at least one clear photo of yourself, your city, your padel level and play style, and fill in the “More about you” details (job, interests, a couple of prompts). The more complete your profile, the better your matches.' },
      { q: 'How does volpair work?',
        a: 'volpair connects padel players who are also open to dating. You discover nearby, compatible players, send a Volley (romantic interest) or a Connect (to play), and when interest is mutual you can message and arrange a game.' },
      { q: 'Do I need to link a padel account?',
        a: 'No — you can self-report your level. Linking a booking platform (e.g. Playtomic) lets us verify your level and match history, which improves your volpair Score.' },
    ],
  },
  {
    slug: 'account',
    emoji: '👤',
    title: 'Profile & account',
    desc: 'Edit your details, control who sees you, pause or delete your account.',
    articles: [
      { q: 'How do I edit my profile?',
        a: 'Go to Profile → Edit Profile. You can change your photos, city, home club, bio, the “More about you” details and your prompts at any time.' },
      { q: 'Who can see my profile?',
        a: 'In Edit Profile you can set “Who can see you?” to Everyone, Women only, or Men only. Other players only ever see your first name — your surname is never shown.' },
      { q: 'How do I pause or hide my profile?',
        a: 'Turn off Radar visibility in your settings to stop appearing in discovery while keeping your account and matches.' },
      { q: 'How do I delete my account?',
        a: 'Go to Profile → Settings → Delete account. This permanently removes your profile, photos, matches and messages. Deletion is irreversible. If you only want a break, hide your profile instead.' },
      { q: 'How do I change my email or password?',
        a: 'Use Profile → Settings for email changes, and “Forgot password” on the login screen to reset your password.' },
    ],
  },
  {
    slug: 'matching',
    emoji: '🎾',
    title: 'Matching & discovery',
    desc: 'Volley, Connect, Play again, the volpair Score and how discovery works.',
    articles: [
      { q: 'What’s the difference between Volley, Connect and Play again?',
        a: 'A Volley 💘 signals romantic interest. A Connect 👋 says you’d like to play padel together. Play again 🎾 appears only with people you’ve already played, to set up a rematch.' },
      { q: 'What is a Match?',
        a: 'When you and another player both send a Volley, it’s a Match — you can then message each other and take it from there.' },
      { q: 'What is the volpair Score?',
        a: 'It’s a compatibility score out of 100 based on your padel level, play style, availability overlap, shared clubs and (if you’ve played) court chemistry. It helps surface players you’re likely to click with on and off court.' },
      { q: 'Why am I seeing certain people?',
        a: 'Discovery shows nearby, active players who match your visibility and dating preferences, sorted by your volpair Score. Use the Nearby/Everywhere toggle on Connect to widen or narrow the range.' },
      { q: 'What does “Nearby” vs “Everywhere” mean?',
        a: 'Nearby shows active players close to you. Everywhere lifts the distance limit so you can browse all eligible players — your visibility and dating preferences still apply.' },
    ],
  },
  {
    slug: 'messaging',
    emoji: '💬',
    title: 'Messaging (Serves)',
    desc: 'Sending messages and managing your conversations.',
    articles: [
      { q: 'How do I message someone?',
        a: 'Once you have a Match (or an accepted Connect), open the conversation and send a Serve — that’s a message on volpair. Either person can message first.' },
      { q: 'Why can’t I message a player?',
        a: 'You can only message people you’re matched or connected with. If you can’t message someone, you may not have a mutual connection yet, or one of you has unmatched or blocked the other.' },
      { q: 'Will I be notified of new messages?',
        a: 'Yes — if you’ve allowed notifications, you’ll get a push when someone sends you a Serve, Volley, Connect or when you Match.' },
    ],
  },
  {
    slug: 'safety-reporting',
    emoji: '🛡️',
    title: 'Safety & reporting',
    desc: 'Block, report and stay safe on and off the court.',
    articles: [
      { q: 'How do I block someone?',
        a: 'Open their profile, tap the “⋯” menu and choose Block. They will no longer see you or be able to contact you, and you won’t see them.' },
      { q: 'How do I report someone?',
        a: 'Open their profile, tap “⋯” → Report, and choose a reason. Reports are confidential — the person is not told who reported them.' },
      { q: 'What happens after I report someone?',
        a: 'Our team reviews reports and may warn, suspend or remove accounts that break our Community Guidelines. Serious or illegal behaviour may be referred to the relevant authorities.' },
      { q: 'How do I stay safe meeting in person?',
        a: 'Meet at the padel club or another public place, tell a friend where you’re going, arrange your own transport, and never send money to someone you’ve met online. See our Safety Centre for more.' },
    ],
  },
  {
    slug: 'subscriptions',
    emoji: '💳',
    title: 'Subscriptions & payments',
    desc: 'Plans, billing, cancelling and refunds.',
    articles: [
      { q: 'Is volpair free?',
        a: 'volpair is free to download and use for core features. Some optional premium features may be offered as a paid subscription.' },
      { q: 'How do I cancel my subscription?',
        a: 'Subscriptions are billed by Apple or Google, so you cancel through your device: iPhone → Settings → your name → Subscriptions; Android → Play Store → Subscriptions. Cancelling stops future renewals; you keep premium until the end of the paid period.' },
      { q: 'Can I get a refund?',
        a: 'Because Apple and Google process payments, refunds are handled by them. See our Subscription & Refund Terms, and request a refund via Apple (reportaproblem.apple.com) or Google Play. UK consumers may also have statutory rights.' },
      { q: 'How do I restore a purchase?',
        a: 'Make sure you’re signed in with the same Apple/Google account you purchased with, then use “Restore purchases” in the app’s subscription screen.' },
    ],
  },
  {
    slug: 'privacy-data',
    emoji: '🔒',
    title: 'Privacy & your data',
    desc: 'How we use your data and how to access or delete it.',
    articles: [
      { q: 'What data does volpair collect?',
        a: 'The information you give us (profile, photos, messages), limited device and location data to power discovery, and, if you link a platform, your padel level and match history. Full details are in our Privacy Policy.' },
      { q: 'How do I download or delete my data?',
        a: 'You can delete your account in-app at any time. To request a copy of your data (a UK GDPR subject access request) or its erasure, email support@volpair.com and we’ll respond within one month.' },
      { q: 'Do you sell my data?',
        a: 'No. We do not sell your personal data. We share it only with the service providers needed to run volpair, as described in our Privacy Policy.' },
    ],
  },
  {
    slug: 'troubleshooting',
    emoji: '🛠️',
    title: 'Troubleshooting',
    desc: 'Fixes for common technical issues.',
    articles: [
      { q: 'I can’t log in',
        a: 'Check your internet connection, make sure you’re using the email you signed up with, and try “Forgot password”. If it still fails, email support@volpair.com.' },
      { q: 'The app is asking me to update',
        a: 'We occasionally require the latest version for safety and reliability. Update volpair from the App Store or Google Play to continue.' },
      { q: 'I’m not seeing any players',
        a: 'Make sure location and Radar visibility are enabled, try the Everywhere toggle on Connect, and check your dating preferences aren’t filtering everyone out.' },
      { q: 'I’m not getting notifications',
        a: 'Enable notifications for volpair in your device settings, and make sure you allowed them when prompted in the app.' },
    ],
  },
];

export function getCategory(slug) {
  return HELP_CATEGORIES.find((c) => c.slug === slug);
}
